
image: Visual Studio 2017
platform:
  - x86
  - x64
configuration: Release

# Restore Nuget packages
before_build:
  - nuget restore Synnduit.sln

# Build
build:
  project: Synnduit.sln
  verbosity: minimal

test_script:
  ps: vstest.console /logger:Appveyor "C:\projects\synnduit\test\Synnduit.Core.Test\bin\x64\Release\Synnduit.Core.Test.dll" "C:\projects\synnduit\test\Synnduit.Test\bin\x64\Release\Synnduit.Test.dll"
